### ISSUE TITLE
Unhandled exception. System.FormatException: Input string was not in a correct format.

### ISSUE THREAD

**Issue by Jarvis4555** [microsoft/winget-create#45] opened 2021-05-29 16:56 UTC
The following is the error I'm getting
```
Unhandled exception. System.FormatException: Input string was not in a correct format.
   at System.Text.ValueStringBuilder.ThrowFormatError()
   at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)
   at Microsoft.WingetCreateCLI.Logging.Logger.Log(LogLevel level, String format, Object[] args)
   at Microsoft.WingetCreateCLI.Logging.Logger.Error(String message, Object[] args)
   at Microsoft.WingetCreateCLI.Program.Main(String[] args)
   at Microsoft.WingetCreateCLI.Program.<Main>(String[] args)
```
I was trying to submit Exodus using wingetcreate. After generating the manifest I have tested the manifest by using this command `winget install --manifest "C:\Users\xxx\manifests\e\Exodus\exodus\21.5.25"`. The application has been successfully installed but when I tried to submit the manifest this error popped out. Please help me out to resolve it.

**Comment by ryfu-msft** [comment] 2021-06-01 23:21
Hey @Jarvis4555 ,

Could you provide some repro steps as to how you got to this point? It would also be helpful if you could share the manifest that you created so I could also try this out. That would help me investigate this issue further. Thanks!

**Comment by palenshus** [comment] 2021-06-03 04:54
I believe this is a duplicate of #49, please reactivate if you disagree

**Closed** 2021-06-03 04:56 UTC
Labels: In-PR, Issue-Bug
