### ISSUE TITLE
Unhandled exception. System.FormatException: Input string was not in a correct format.

### ISSUE THREAD

**Issue by RamonRobben** [microsoft/winget-create#57] opened 2021-06-02 17:31 UTC
Hello while making a manifest file for Docker I received the following error:

```
Unhandled exception. System.FormatException: Input string was not in a correct format.
   at System.Text.ValueStringBuilder.ThrowFormatError()
   at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)
   at Microsoft.WingetCreateCLI.Logging.Logger.Log(LogLevel level, String format, Object[] args)
   at Microsoft.WingetCreateCLI.Logging.Logger.Error(String message, Object[] args)
   at Microsoft.WingetCreateCLI.Program.Main(String[] args)
   at Microsoft.WingetCreateCLI.Program.<Main>(String[] args)
```

# Steps to reproduce

1. Enter URL: _https://desktop.docker.com/win/stable/amd64/Docker%20Desktop%20Installer.exe_
2. Press enter 7 times until you get to ShortDescription
3. Change short description to _Docker Desktop for Windows_
4. Press Enter
5. Would you like to make changes? Press Y and then Enter
6. Press Enter for the remaining questions
7. Then press Y and Enter to submit to package manager repository
8. Fill in the github code and Enter
9. Fill in Password and press Enter
10. Then error shows up

**Comment by ryfu-msft** [comment] 2021-06-02 18:13
Hi @RamonRobben,

Thank you for this, I will investigate this bug further. Were you still able to submit a pull request or did the error terminate before that process could take place? I'm not seeing your PR in winget-pkgs so I'm assuming no.

**Comment by RamonRobben** [comment] 2021-06-02 18:16
> Hi @RamonRobben,
> 
> Thank you for this, I will investigate this bug further. Were you still able to submit a pull request or did the error terminate before that process could take place? I'm not seeing your PR in winget-pkgs so I'm assuming no.

Hey, No unfortunately it did not submit a PR. I did however try to do it manually but it seems that there is already a package with that software. It just had a different name then what the program came up with. (DockerInc. vs Docker) And some different subfolder names.

**Comment by ryfu-msft** [comment] 2021-06-02 19:52
That's good to know! Regardless, we appreciate your contribution to our tool :) We are currently working on adding logic to the tool to check for existing packages to help avoid submitting duplicates. In case you didn't know, you can quickly check if a package already exists by entering `winget search Docker` in terminal or by searching for the package in the [winget-pkgs repo](https://github.com/microsoft/winget-pkgs).  Thanks again!

> > Hi @RamonRobben,
> > Thank you for this, I will investigate this bug further. Were you still able to submit a pull request or did the error terminate before that process could take place? I'm not seeing your PR in winget-pkgs so I'm assuming no.
> 
> Hey, No unfortunately it did not submit a PR. I did however try to do it manually but it seems that there is already a package with that software. It just had a different name then what the program came up with. (DockerInc. vs Docker) And some different subfolder names.

**Comment by palenshus** [comment] 2021-06-03 04:57
I believe this is a duplicate, please reactivate if you disagree

Duplicate of #49

**Closed by palenshus** 2021-06-03 04:57 UTC
Labels: In-PR, Issue-Bug
