### ISSUE TITLE
Allow updating a manifest with a different number of installer URLs

### ISSUE THREAD

**Issue by RuiNtD** [microsoft/winget-create#291] opened 2022-07-23 14:32 UTC
### Description of the new feature / enhancement

Hello. I'm trying to update a package (`PolyMC.PolyMC`) that has stopped distributing 64-bit exes and I can't update the manifest because of this error:
> Updating a manifest is only supported with the same number of installer URLs.

This error should be a warning instead, prompting the user if they want to continue anyways.

**Comment by Trenly** [comment] 2022-07-23 21:55
@FayneAldan - Just an FYI; PolyMC actually has a bot that submits their releases automatically https://github.com/microsoft/winget-pkgs/pull/67332

**Comment by FayneAldan** [comment] 2022-07-23 21:57
Yes, I am aware. I tried to update the package manually after Winget Releaser picked the wrong installers, but Winget Create wouldn't let me do it.

**Comment by ryfu-msft** [comment] 2022-07-25 20:57
Hey @FayneAldan, 

We actually do support your scenario. The reason why it didn't work is because the manifest of the latest version of PolyMC (v1.4) only has one installer URL which has already been checked in. We always use the latest version for the update. If that manifest wasn't checked in, you could have done something like this:

`wingetcreate update PolyMC.PolyMC --urls "https://github.com/PolyMC/PolyMC/releases/download/1.3.0/PolyMC-Windows-x86_64-Setup-1.3.0.exe" "https://github.com/PolyMC/PolyMC/releases/download/1.3.0/PolyMC-Windows-i686-Setup-1.3.0.exe"`

Winget-Create already has logic to help match the installers with the correct architecture but if you find that it didn't match it correctly, you can also override the detected architecture:

`wingetcreate update PolyMC.PolyMC --urls "https://github.com/PolyMC/PolyMC/releases/download/1.3.0/PolyMC-Windows-x86_64-Setup-1.3.0.exe|x64" "https://github.com/PolyMC/PolyMC/releases/download/1.3.0/PolyMC-Windows-i686-Setup-1.3.0.exe|x86"`

Just fyi, in case you ever try this again in the future :)

**Comment by Jaifroid** [comment] 2022-07-28 17:56
Well, I'm also getting this error but with manifests that have two entries for the SAME installer/architecture, due to scope `user` and scope `machine`. Latest version of winget-create errors out when trying to update manifest with these entries (only the installer entries shown here):

```
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/kiwix/kiwix-js-windows/releases/download/v2.0.9/Kiwix-JS-Electron-Setup-2.0.9-E.exe
  InstallerSha256: AFE82A7B77ADFD259B336BB0DFE85D88098CDB43DCC6C307E35D1922233EA8E7
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/kiwix/kiwix-js-windows/releases/download/v2.0.9/Kiwix-JS-Electron-Setup-2.0.9-E.exe
  InstallerSha256: AFE82A7B77ADFD259B336BB0DFE85D88098CDB43DCC6C307E35D1922233EA8E7
  InstallerSwitches:
    Custom: /ALLUSERS
```

This used to work, so it's a recent issue.

**Comment by Jaifroid** [comment] 2022-07-28 17:59
NB, same error with two scopes and one installer is mentioned back in 2021 here: https://github.com/microsoft/winget-pkgs/issues/500#issuecomment-932892281. The version of winget-create I was using was even older, I think, and I only recently updated to the latest version, hitting this error each time I try to update that and similar manifests for my app. I've been having to calculate the SHAs using PowerShel and update manifests manually, though I'll give https://github.com/vedantmgoyal2009/winget-releaser a go.

**Comment by ryfu-msft** [comment] 2022-08-03 17:04
@Jaifroid, thanks for bringing this to my attention. Looks like this is a bug that I will need to fix to address the scenario where the same installerURL is being used for multiple architectures. Will work on a fix for this...

**Comment by Jaifroid** [comment] 2022-08-03 20:07
@ryfu-mfst Thanks for picking this up. Just to note, that in my case it's not different architectures that are causing the winget-create issue, it is different installer scopes: Scope: user and Scope: machine. The architecture is the same in both cases (x86).


@Jaifroid<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJaifroid&data=05%7C01%7Cegk10%40universityofcambridgecloud.onmicrosoft.com%7C1e1b43557aea42dcd16808da75725491%7C49a50445bdfa4b79ade3547b4f3986e9%7C0%7C0%7C637951431141063730%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ic4FNGWk5TRgUSykpu3tjR%2BuPn%2BWKzsnc35vYSD3dXw%3D&reserved=0>, thanks for bringing this to my attention. Looks like this is a bug that I will need to fix to address the scenario where the same installerURL is being used for multiple architectures. Will work on a fix for this...

**Comment by iqfareez** [comment] 2022-08-11 06:41
> Well, I'm also getting this error but with manifests that have two entries for the SAME installer/architecture, due to scope `user` and scope `machine`. Latest version of winget-create errors out when trying to update manifest with these entries (only the installer entries from the manifest are shown here):
> 
> ```
> Installers:
> - Architecture: x86
>   Scope: user
>   InstallerUrl: https://github.com/kiwix/kiwix-js-windows/releases/download/v2.0.9/Kiwix-JS-Electron-Setup-2.0.9-E.exe
>   InstallerSha256: AFE82A7B77ADFD259B336BB0DFE85D88098CDB43DCC6C307E35D1922233EA8E7
>   InstallerSwitches:
>     Custom: /CURRENTUSER
> - Architecture: x86
>   Scope: machine
>   InstallerUrl: https://github.com/kiwix/kiwix-js-windows/releases/download/v2.0.9/Kiwix-JS-Electron-Setup-2.0.9-E.exe
>   InstallerSha256: AFE82A7B77ADFD259B336BB0DFE85D88098CDB43DCC6C307E35D1922233EA8E7
>   InstallerSwitches:
>     Custom: /ALLUSERS
> ```
> 
> This used to work, so it's a recent issue.

Same issue here. Workaround that maybe can work is to pass the `--interactive` flag to `wingetcreate update <PackageName>`.

**Comment by cderv** [comment] 2022-09-12 13:48
Related to https://github.com/microsoft/winget-create/issues/166 IMO

**Comment by Jaifroid** [comment] 2022-09-12 19:57
The thing is, this used to work before September 2021, then an update broke it. Whichever dev is working on wingetcreate, I think this needs to be a priority. One of the main reasons to use wingetcreate is in automated build and publishing, but it's currently causing me to have to intervene manually (in a laborious way) each time I prepare a new release. I'm about to give up and just write an automated powershell script to grab the SHA and forcibly update the mainfest values, but this won't do any of the testing and validation that is a great benefit of wingetcreate.

**Comment by Jaifroid** [comment] 2022-11-05 12:16
Is there any update on allowing wingetcreate to update manifests that have the same package listed for different scopes (per user and per machine)? It's currently unusable, as it errors out, saying that a manifest shouldn't have the same package listed twice. This is clearly a bug, because we don't need different packages for different scopes. Usually it's just a quesiton of changing an installer flag on the commandline. This used to work in wingetcreate, before September 2021. It should be an easy fix.

**Comment by jakopo87** [comment] 2023-01-21 08:54
I'm having the same problem trying to update the package "TheDocumentFoundation.LibreOffice.HelpPack" to a new version and adding installers for other locales.

**Comment by tikkanz** [comment] 2023-03-14 04:32
Having the same problem reported above by @Jaifroid  updating the package `Jsoftware.J.9.4` with 2 installer entries (both the same .exe) for `machine` & `user` scopes. Using the tool interactively works OK but isn't a solution for CI.
Any idea on the likely timeframe for this to be fixed?

**Comment by mdanish-kh** [comment] 2023-05-25 16:38
cc @denelon Resolved in WinGet-Create 1.2.6.0

**Closed** 2023-05-25 17:02 UTC
Labels: Issue-Bug

**Comment by Jaifroid** [comment] 2023-06-02 17:41
@mdanish-kh @denelon Thanks for the update and the advice to use overrides. I've now tested this, and although the overrides work, I do not consider this issue to be fully fixed for my use case. Wingetcreate, with overrides for per user and per machine on the same bundle or executable, downloads the exact same archive twice.

Since I am frequently (at least twice a month) validating and submitting manifests for executables of 1GB and 1.6GB, this is very unfortunate, and definitely not necessary. Wingetcreate should check the URL, and not process identical URLs twice, as it has already worked out the hash.

The commandline I'm useing is:

`wingetcreate.exe update <AppID> -v 2.5.0-E -u "<URL>|x86|machine" "<URL>|x86|user" -s -t *********`

The `<URL>` here is identical. I am simply tying to get wingetcreate to update a manifest that has two scopes for one bundle. This used to work fantastically in an earlier version of wingetcreate. Unfortunately, this behaviour means I still can't use wingetcreate, which is a shame.

If you think it's best to open a new issue, I'll be happy to do so.

**Comment by mdanish-kh** [comment] 2023-06-02 17:57
@Jaifroid I can definitely see how that's annoying. The request is being tracked here
- #312

**Comment by stevapple** [comment] 2023-09-21 18:30
I don't think the issue is really resolved. It's still impossible to add or remove an installer option using `wingetcreate update`.

**Comment by mdanish-kh** [comment] 2023-09-21 18:53
@stevapple The original issue was more related to the fact that the PR creation failed even when matching the number of URLs in the previous manifest

Your request is being partially tracked in https://github.com/microsoft/winget-create/issues/351 (request for an option like `--add` to add additional installers). There isn't one for remove since that doesn't seem to be popular use case. You can create an issue for that explaining your use case for the command

**Comment by stevapple** [comment] 2023-09-22 00:21
@mdanish-kh Thanks for pointing out! Maybe this issue can have a new title to more accurately reflect the status quo?
