### ISSUE TITLE
wingetcreate should not allow submission when the application already exists.

### ISSUE THREAD

**Issue by KaranKad** [microsoft/winget-create#39] opened 2021-05-30 07:36 UTC
# Description of the new feature/enhancement

wingetcreate should not allow submission of already existing manifest.
# Proposed technical implementation details (optional)
Use sha256 for identifying.

**Comment by palenshus** [comment] 2021-06-03 21:15
Duplicate of #34

**Closed by palenshus** 2021-06-03 21:15 UTC
Labels: Issue-Feature
